// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trjoqzvruzwuiggdwdki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyam9xenZydXp3dWlnZ2R3ZGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTk2MzIsImV4cCI6MjA2OTMzNTYzMn0.fhL6UEcvcgmESdUkQVq0ukWK1TGq2CjBV6VswvTikAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});